version: '2'

services:
  mariadb:
    build: ./mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "root"